### ISSUE TITLE
how can we use ozIMMU with smaller mattrix size?

### ISSUE THREAD

**Issue by jdomke** [enp1s0/ozIMMU#1]
i'm trying ozIMMU and our inputs are not large enough to fullfil the condition below
https://github.com/enp1s0/ozIMMU/blob/0fa0382fb3151896d69c4de6769f1a2dd6f4aa00/src/cublas.cu#L163

what i'm doing is intercepting a dgemm_ call, moving the matrices to gpu, trying to exec ozIMMU on them, and moving the result back into host memory. doing all of this is fine with cublas, but breaks if i remove the `m >= 1024 && n >= 1024 && k >= 1024` check to force ozIMMU for our smaller matrices

when i removed the check, then i'm seeing crashes (with culip enabled; the offload_dgemm info comes from me):
```
[ozIMMU LOG] Initializing ozIMMU handle...
[ozIMMU LOG] Initializing ozIMMU handle
[ozIMMU LOG] Successfully initialized
[ozIMMU LOG] Reallocated moery : 31473664 B
[CULiP Result][Dfp64_int8_4-TN-m7-n68-k68] 3426590ns
offload_dgemm: l,ta,tb,m,n,k,lda,ldb,ldc=0, 0, 0, 7, 61, 68, 7, 68, 7
terminating with uncaught exception of type std::runtime_error: misaligned address [/home/users/jens.domke/will/ozIMMU/src/culip.cu:33 in launch_function]
```

without culip:
```
[ozIMMU LOG] Initializing ozIMMU handle...
[ozIMMU LOG] Initializing ozIMMU handle
[ozIMMU LOG] Successfully initialized
[ozIMMU LOG] Reallocated moery : 31473664 B
offload_dgemm: l,ta,tb,m,n,k,lda,ldb,ldc=0, 0, 0, 7, 61, 68, 7, 68, 7
CUDA error at /home/users/jens.domke/will/ozIMMU/src/offload_dgemm.cpp:103 code=716(cudaErrorMisalignedAddress) "cudaMemcpy(oC, C, memSizeC, cudaMemcpyDeviceToHost)" 
```

my guess is that the memory of C gets corrupted by ozIMMU somehow. can we get this working for m,n,k<1024 ?

**Comment by enp1s0** [comment]
@jdomke Thank you for the issue. Can you show me the arguments of the DGEMM call? The CULiP and offload_dgemm logs show different arguments, e.g. the CULiP log shows that the matmul form (m, n, k) is (7, 68, 68) while offload_dgemm shows (7, 61, 68).

**Comment by enp1s0** [comment]
Also, I added argument checking to the internal GEMM function. Can you pull the latest commit and run it again?

**Comment by jdomke** [comment]
this might have been an artifact from mixing printf, cerr, etc. i have now improved the writing with fflush. and the log before the crash is as follows:
```
 DGEMM with TN           7          68          68          68          68           7
offload_dgemm: l,ta,tb,m,n,k,lda,ldb,ldc=0, 1, 0, 7, 68, 68, 68, 68, 7
[ozIMMU LOG] Initializing ozIMMU handle...
[ozIMMU LOG] Initializing ozIMMU handle
[ozIMMU LOG] Successfully initialized
[ozIMMU LOG] Reallocated moery : 31473664 B
cublas: Dfp64_int8_4-TN-m7-n68-k68
[CULiP Result][Dfp64_int8_4-TN-m7-n68-k68] 3450774ns
 DGEMM with NN           7          61          68           7          68           7
offload_dgemm: l,ta,tb,m,n,k,lda,ldb,ldc=0, 0, 0, 7, 61, 68, 7, 68, 7
cublas: Dfp64_int8_4-NN-m7-n61-k68
terminating with uncaught exception of type std::runtime_error: misaligned address [/home/users/jens.domke/will/ozIMMU/src/culip.cu:33 in launch_function]
```

**Comment by enp1s0** [comment]
Thank you for the log. I have reproduced the crash on my side. I'll investigate the cause, so please wait a while.

**Comment by enp1s0** [comment]
@jdomke I fixed the bug. Can you pull the latest commit and run the program again? Also, I added environment variables to set the threshold of `m`, `n`, and `k` to control the cuBLAS GEMM interception. Please set these variables:
```bash
export OZIMMU_INTERCEPT_THRESHOLD_M=0
export OZIMMU_INTERCEPT_THRESHOLD_N=0
export OZIMMU_INTERCEPT_THRESHOLD_K=0
```
instead of removing `m >= 1024 && n >= 1024 && k >= 1024`. The default threshold is 1024. (But I don't recommend using ozIMMU for small GEMMs because it's slow. That's why I set the threshold)

**Comment by jdomke** [comment]
> @jdomke I fixed the bug. Can you pull the latest commit and run the program again? Also, I added environment variables to set the threshold of `m`, `n`, and `k` to control the cuBLAS GEMM interception. Please set these variables:
> 
> ```shell
> export OZIMMU_INTERCEPT_THRESHOLD_M=0
> export OZIMMU_INTERCEPT_THRESHOLD_N=0
> export OZIMMU_INTERCEPT_THRESHOLD_K=0
> ```
> 
> instead of removing `m >= 1024 && n >= 1024 && k >= 1024`. The default threshold is 1024. (But I don't recommend using ozIMMU for small GEMMs because it's slow. That's why I set the threshold)

great, thanks, it seems to have fixed the problem for us

**Comment by jdomke** [comment]
appreciate your help
